source/FlowplaneExtensions/Controllers/WrikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using FlowplaneExtensions.Models.api.Flow;
using Newtonsoft.Json;

using FlowplaneExtensions.Models.api;

namespace FlowplaneExtensions.Controllers
{
    public class WrikeController : Controller
    {
        public ActionResult Auth()
        {
            return View();
        }

        public ActionResult Header()
        {
            return View();
        }

        public ActionResult Body()
        {
            return View();
        }

        [HttpPost]
        public ActionResult oauth(string txtWrikeConsumerKey, string txtWrikeConsumerSecret)
        {
            TempData["txtWrikeConsumerKey"] = txtWrikeConsumerKey;
            TempData["txtWrikeConsumerSecret"] = txtWrikeConsumerSecret;

            if (string.IsNullOrEmpty(txtWrikeConsumerKey) && string.IsNullOrEmpty(txtWrikeConsumerSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getloginurl/{0}?returnurl={1}",
                                  new Extensions.Wrike.Identity().Code,
                                  Request.Url.AbsoluteUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var tokens = JsonConvert.DeserializeObject<string>(rs.Content.ReadAsStringAsync().Result);

                var split = tokens.Split('&');
                TempData["WrikeRequestTokenSecret"] = split[1].Substring(split[1].IndexOf("=") + 1);

                return Redirect(string.Format("https://www.wrike.com/rest/auth/authorize?{0}", tokens));
            }
            else
            {
                var auth = new Extensions.Wrike.Tokens(new Extensions.Wrike.Auth(txtWrikeConsumerKey, txtWrikeConsumerSecret, null, null, Request.Url.AbsoluteUri));
                var tokens = auth.GetRequestToken();
                var split = tokens.Split('&');
                TempData["WrikeRequestTokenSecret"] = split[1].Substring(split[1].IndexOf("=") + 1);

                return Redirect(string.Format("https://www.wrike.com/rest/auth/authorize?{0}", tokens));
            }
        }

        public ActionResult oauth()
        {
            if (Request["oauth_token"] == null)
                throw new Exception("Invalid auth token.");

            var txtWrikeConsumerKey = TempData["txtWrikeConsumerKey"].ToString();
            var txtWrikeConsumerSecret = TempData["txtWrikeConsumerSecret"].ToString();
            var redirectUri = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority) + System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            string[] tokens;
            if (string.IsNullOrEmpty(txtWrikeConsumerKey) && string.IsNullOrEmpty(txtWrikeConsumerSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getaccesstokens/{0}?wrikeauthtoken={1}&wrikeauthtokensecret={2}&returnurl={3}",
                                  new Extensions.Wrike.Identity().Code,
                                  Request["oauth_token"],
                                  TempData.Peek("WrikeRequestTokenSecret").ToString(),
                                  redirectUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                tokens = JsonConvert.DeserializeObject<Dictionary<string, string>>(rs.Content.ReadAsStringAsync().Result)["AccessToken"].Split('&');
            }
            else
            {
                var auth = new Extensions.Wrike.Tokens(new Extensions.Wrike.Auth(txtWrikeConsumerKey, txtWrikeConsumerSecret, Request["oauth_token"], TempData.Peek("WrikeRequestTokenSecret").ToString(), redirectUri));
                tokens = auth.GetAccessToken().Split('&');
            }

            var oauth_token = tokens[0].Substring(tokens[0].IndexOf("=") + 1);
            var oauth_token_secret = tokens[1].Substring(tokens[1].IndexOf("=") + 1);

            ViewBag.WrikeAccessToken = oauth_token;
            ViewBag.WrikeAccessTokenSecret = oauth_token_secret;

            return View("OAuthComplete");
        }

        public ActionResult FlowDetail(string fpxtpms)
        {
            if (string.IsNullOrEmpty(fpxtpms)) return View();

            ViewBag.pms = fpxtpms;
            return View(JsonConvert.DeserializeObject<Detail>(System.Uri.UnescapeDataString(fpxtpms)));
        }
    }
}

source/FlowplaneExtensions/Views/Wrike/Auth.cshtml
<script>
    var wrikeAuthPopup = function () {
        var w = 1000;
        var h = 640;
        var left = (screen.width / 2) - (w / 2);
        var top = (screen.height / 2) - (h / 2);
        window.open("about:blank",
                 "frmWrikeAuth",
                 "width=" + w + ", height=" + h + ", top=" + top + ", left=" + left + ", toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no");
        document.getElementById('frm-wrike-app-keys').submit();
    }
    $(document).ready(function () {
        $('#chkWrikeOauthOption').bootstrapSwitch().on('switchChange.bootstrapSwitch', function (event, state) {
            if (state == false) {
                $('.wrike-app-keys').show();
                $('#txtWrikeConsumerKey').focus();
            } else {
                $('#txtWrikeConsumerKey').val('');
                $('#txtWrikeConsumerSecret').val('');
                $('.wrike-app-keys').hide();
            }
        });
    });
</script>

    <div class="form-group">
        <label class="col-sm-11">
            <img src="@Url.Content("~//Content/img/ext-wrike.png")" />
            &nbsp;
            Connect to your wrike account.
        </label>
</div>
<div id="btnConnectWrike" class="row" style="margin-top: 20px;">
	<div class="col-md-6">
		<p>
			Oauth with Flowplane:&nbsp;
			<input type="checkbox" id="chkWrikeOauthOption" data-size="medium" data-on-text="Yes" data-off-text="No" checked>
		</p>
		<form id="frm-wrike-app-keys" method="post" action="@Url.Action("oauth", "Wrike")" target="frmWrikeAuth">
			<div class="wrike-app-keys" class="form-group" style="display: none; margin-bottom: 20px;">
				<label>
					Consumer Key:
				</label>
				<input id="txtWrikeConsumerKey" name="txtWrikeConsumerKey" class="form-control" autocomplete="off" placeholder="Consumer Key" type="text" value="" />
			</div>
			<div class="wrike-app-keys" class="form-group" style="display: none;">
				<label>
					Consumer Secret:
				</label>
				<input id="txtWrikeConsumerSecret" name="txtWrikeConsumerSecret" class="form-control" autocomplete="off" placeholder="Consumer Secret" type="text" value="" />
			</div>
		</form>
	</div>
	<div class="col-md-1"></div>
	<div class="col-md-3">
            <a href="javascript:;"
               onclick="wrikeAuthPopup();"
               class="btn green" target="_top">Connect to Wrike</a>
    </div>
	
</div>
  <input id="txtWrikeAccessToken" name="txtWrikeAccessToken" style="visibility: hidden;" type="text" value="" />
        <input id="txtWrikeAccessTokenSecret" name="txtWrikeAccessTokenSecret" style="visibility: hidden;" type="text" value="" />
<h4 id="lblConnectedToWrike" style="display: none;"><i class="fa fa-check"></i>&nbsp; Connected.</h4>

source/FlowplaneExtensions/Views/Wrike/Body.cshtml
<form class="form-horizontal" role="form">
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div id="dlg-ProcObjProperties-error" class="col-sm-8" style="color: #c00;"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Create task:
        </label>
        <div class="col-sm-8">
            <input type="text" class="form-control" name="txtActivityParamTaskDesc" id="txtActivityParamTaskDesc" placeholder="Task Name (required)" maxlength="1000" style="width:100%" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Folders:
        </label>
        <div class="col-sm-8">
            <div id="folders-loading" class="frmLoader" style="width: 440px">
                &nbsp;Loading folders...
            </div>
            <div id="treeActivityParamFolders" class="jstree jstree-default" role="tree">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Assignee:
        </label>
        <div class="col-sm-8">
            <div id="assignees-loading" class="frmLoader" style="width: 440px">
                &nbsp;Loading assignees...
            </div>
            <select id="cboActivityParamAssignee" class="form-control" style="width: 440px"></select>
        </div>
    </div>
</form>

source/FlowplaneExtensions/Views/Wrike/FlowDetail.cshtml
@using Microsoft.Ajax.Utilities
@model FlowplaneExtensions.Models.api.Flow.Detail

<script src='@Url.Content("~/Content/js/moment/moment.js")' type='text/javascript'></script>
<script src='@Url.Content("~/Content/js/forms/apptools.js")' type='text/javascript'></script>
<script>
    $(document).ready(function () {
        fpxt.forms.apptools.fmtDate($('#dtAssigned'), 'll');
    });
</script>

<h5><img src="@Url.Content("~//Content/img/ext-wrike.png")" /> &nbsp; Wrike Task</h5>

<form class="form-horizontal" role="form">
    <div class="row">
        <div class="col-sm-5">
            <p>
                Description:
            </p>
        </div>
        <div class="col-sm-7">
            <p>
                @Model.GetParamValue("taskdesc")
            </p>
        </div>
    </div>

    @if (Model.DateCreated != null)
    {
        <div class="row">
            <div class="col-sm-5">
                <p>
                    Assigned on:
                </p>
            </div>
            <div class="col-sm-7">
                <p id="dtAssigned">@Convert.ToDateTime(Model.DateCreated).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'")</p>
            </div>
        </div>
    }

    <div class="row">
        <div class="col-sm-5">
            <p>
                Assigned to:
            </p>
        </div>
        <div class="col-sm-7">
            <p>
                @Model.GetParamValue("taskassigneename")
            </p>
        </div>
    </div>
</form>

source/FlowplaneExtensions/Views/Wrike/Header.cshtml
<h4>
    <img src="@System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~//Content/img/ext-wrike.png")" />
    &nbsp; Wrike
</h4>

source/FlowplaneExtensions/Views/Wrike/OAuthComplete.cshtml
<html>
<head>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
    <script>
        window.opener.document.getElementById('txtWrikeAccessToken').value = '@Html.Raw(ViewBag.WrikeAccessToken)';
        window.opener.document.getElementById('txtWrikeAccessTokenSecret').value = '@Html.Raw(ViewBag.WrikeAccessTokenSecret)';
        var btn = $(window.opener.document).find('#btnConnectWrike');
        var lbl = $(window.opener.document).find('#lblConnectedToWrike');
        $(btn).hide();
        $(lbl).show();

        window.close();
    </script>
</head>
<body>
</body>
</html>