source/FlowplaneExtensions/Controllers/TwitterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Extensions.Asana.Responses.Projects;
using FlowplaneExtensions.Models.api;
using FlowplaneExtensions.Models.api.Flow;
using Newtonsoft.Json;

namespace FlowplaneExtensions.Controllers
{
    public class TwitterController : Controller
    {
        public ActionResult Auth()
        {
            return View();
        }

        public ActionResult Header()
        {
            return View();
        }

        public ActionResult Body()
        {
            return View();
        }

        [HttpPost]
        public ActionResult oauth(string txtTwitterConsumerKey, string txtTwitterConsumerSecret)
        {
            TempData["txtTwitterConsumerKey"] = txtTwitterConsumerKey;
            TempData["txtTwitterConsumerSecret"] = txtTwitterConsumerSecret;

            if (string.IsNullOrEmpty(txtTwitterConsumerKey) && string.IsNullOrEmpty(txtTwitterConsumerSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getloginurl/{0}?returnurl={1}",
                                  new Extensions.Twitter.Identity().Code, Request.Url.AbsoluteUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var url = JsonConvert.DeserializeObject<string>(rs.Content.ReadAsStringAsync().Result);

                return Redirect(HttpUtility.UrlDecode(url));
            }
            else
            {
                var auth = new Extensions.Twitter.Auth(txtTwitterConsumerKey, txtTwitterConsumerSecret, "", "");
                return Redirect(HttpUtility.UrlDecode(auth.GetLoginUrl(Request.Url.AbsoluteUri)));
            }
        }

        public ActionResult oauth()
        {
            if (Request["oauth_token"] == null || Request["oauth_verifier"] == null)
                throw new Exception("Invalid auth codes.");

            var txtTwitterConsumerKey = TempData["txtTwitterConsumerKey"].ToString();
            var txtTwitterConsumerSecret = TempData["txtTwitterConsumerSecret"].ToString();

            if (string.IsNullOrEmpty(txtTwitterConsumerKey) && string.IsNullOrEmpty(txtTwitterConsumerSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getaccesstokens/{0}?twitterOauthToken={1}&twitterOauthVerifier={2}",
                                  new Extensions.Twitter.Identity().Code,
                                  Request["oauth_token"],
                                  Request["oauth_verifier"])).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var tokens = JsonConvert.DeserializeObject<Dictionary<string, string>>(rs.Content.ReadAsStringAsync().Result);

                ViewBag.AccessToken = tokens["AccessToken"];
                ViewBag.AccessTokenSecret = tokens["AccessTokenSecret"];
            }
            else
            {
                var auth = new Extensions.Twitter.Auth(txtTwitterConsumerKey, txtTwitterConsumerSecret, "", "");
                var tokens = auth.GetAccessTokens(Request["oauth_token"], Request["oauth_verifier"]);

                ViewBag.AccessToken = tokens["AccessToken"];
                ViewBag.AccessTokenSecret = tokens["AccessTokenSecret"];
            }

            return View("OAuthComplete");
        }

        public ActionResult FlowDetail(string fpxtpms)
        {
            if (string.IsNullOrEmpty(fpxtpms)) return View();

            ViewBag.pms = fpxtpms;
            return View(JsonConvert.DeserializeObject<Detail>(System.Uri.UnescapeDataString(fpxtpms)));
        }
    }
}

source/FlowplaneExtensions/Views/Twitter/Auth.cshtml
<script>
	var twitterAuthPopup = function () {
		var w = 1000;
		var h = 640;
		var left = (screen.width / 2) - (w / 2);
		var top = (screen.height / 2) - (h / 2);
		window.open("about:blank",
			"frmTwitterAuth",
			"width=" + w + ", height=" + h + ", top=" + top + ", left=" + left + ", toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no");
		document.getElementById('frm-twitter-consumer-keys').submit();
	};
	$(document).ready(function () {
		$('#chkTwitterOauthOption').bootstrapSwitch().on('switchChange.bootstrapSwitch', function (event, state) {
			if (state == false) {
				$('.twitter-consumer-keys').show();
				$('#txtTwitterConsumerKey').focus();
			} else {
				$('.twitter-consumer-keys').hide();
			}
		});
	});
</script>
<p>
	<img src="@Url.Content("~/Content/img/ext-twitter.png")" />
	&nbsp;
	Connect to your Twitter account.
</p>
<div id="btnConnectTwitter" class="row" style="margin-top: 20px;">
	<div class="col-md-6">
		<p>
			Oauth with Flowplane:&nbsp;
			<input type="checkbox" id="chkTwitterOauthOption" data-size="medium" data-on-text="Yes" data-off-text="No" checked>
		</p>
		<form id="frm-twitter-consumer-keys" method="post" action="@Url.Action("oauth", "Twitter")" target="frmTwitterAuth">
			<div class="twitter-consumer-keys" class="form-group" style="display: none; margin-bottom: 20px;">
				<label>
					Consumer Key:
				</label>
				<input id="txtTwitterConsumerKey" name="txtTwitterConsumerKey" class="form-control" autocomplete="off" placeholder="Consumer Key" type="text" value="" />
			</div>
			<div class="twitter-consumer-keys" class="form-group" style="display: none;">
				<label>
					Consumer Secret:
				</label>
				<input id="txtTwitterConsumerSecret" name="txtTwitterConsumerSecret" class="form-control" autocomplete="off" placeholder="Consumer Secret" type="text" value="" />
			</div>
		</form>
	</div>
	<div class="col-md-1"></div>
	<div class="col-md-3">
		<a href="javascript:;"
		   onclick="twitterAuthPopup();"
		   class="btn green" target="_top">Connect to Twitter</a>
	</div>
</div>

<input id="txtTwitterAccessToken" name="txtTwitterAccessToken" style="visibility: hidden;" type="text" value="" />
<input id="txtTwitterAccessTokenSecret" name="txtTwitterAccessTokenSecret" style="visibility: hidden;" type="text" value="" />
<h4 id="lblConnectedToTwitter" style="display: none;"><i class="fa fa-check"></i>&nbsp; Connected.</h4>

source/FlowplaneExtensions/Views/Twitter/Body.cshtml
<form class="form-horizontal" role="form">
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div id="dlg-ProcObjProperties-error" class="col-sm-8" style="color: #c00;"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Compose tweet:
        </label>
        <div class="col-sm-8">
            <textarea id="txtEventParamTweetStatus" name="txtEventParamTweetStatus" placeholder="Tweet status (required)" maxlength="140"
                      style="resize: none; width: 100%; min-height: 140px; max-height: 140px; min-width: 100%; max-width: 100%;"
                      class="form-control"></textarea>
        </div>
    </div>
</form>

source/FlowplaneExtensions/Views/Twitter/FlowDetail.cshtml
@model FlowplaneExtensions.Models.api.Flow.Detail

<script src='@Url.Content("~/Content/js/moment/moment.js")' type='text/javascript'></script>
<script src='@Url.Content("~/Content/js/forms/apptools.js")' type='text/javascript'></script>
<script>
    $(document).ready(function () {
        fpxt.forms.apptools.fmtDate($('#dtStarted'), 'll');
    });
</script>

<h5><i class="fa fa-twitter fa-2x" style="margin-right: 10px; color: #55acee;"></i>Twitter Event</h5>

<p>
    Tweet status:<br />
</p>
<p>
    @Model.GetParamValue("tweetstatus")
</p>
@if (Model.DateCreated != null)
{
    <p>
        Raised: 
        <span id="dtStarted">@Convert.ToDateTime(Model.DateCreated).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'")</span>
    </p>
}

source/FlowplaneExtensions/Views/Twitter/Header.cshtml
<h4>
    <img src="@Url.Content("~//Content/img/ext-twitter.png")" />
    &nbsp; Twitter
</h4>

source/FlowplaneExtensions/Views/Twitter/OAuthComplete.cshtml
<html>
<head>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
    <script>
        window.opener.document.getElementById('txtTwitterAccessToken').value = '@Html.Raw(ViewBag.AccessToken)';
        window.opener.document.getElementById('txtTwitterAccessTokenSecret').value = '@Html.Raw(ViewBag.AccessTokenSecret)';

        var btn = $(window.opener.document).find('#btnConnectTwitter');
        var lbl = $(window.opener.document).find('#lblConnectedToTwitter');
        $(btn).hide();
        $(lbl).show();

        window.close();
    </script>
</head>
<body>
</body>
</html>