source/FlowplaneExtensions/Controllers/LinkedInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Extensions.Asana.Responses.Projects;
using FlowplaneExtensions.Models.api;
using Newtonsoft.Json;

namespace FlowplaneExtensions.Controllers
{
    public class LinkedInController : Controller
    {
        public ActionResult Auth()
        {
            return View();
        }
        public ActionResult Header()
        {
            return View();
        }
        public ActionResult Body()
        {
            return View();
        }

        [HttpPost]
        public ActionResult oauth(string txtLinkedInApiKey, string txtLinkedInApiSecret)
        {
            TempData["txtLinkedInApiKey"] = txtLinkedInApiKey;
            TempData["txtLinkedInApiSecret"] = txtLinkedInApiSecret;

            if (string.IsNullOrEmpty(txtLinkedInApiKey) && string.IsNullOrEmpty(txtLinkedInApiSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getloginurl/{0}?returnurl={1}",
                                  new Extensions.LinkedIn.Identity().Code, Request.Url.AbsoluteUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var url = JsonConvert.DeserializeObject<string>(rs.Content.ReadAsStringAsync().Result);

                return Redirect(HttpUtility.UrlDecode(url));
            }
            else
            {
                var auth = new Extensions.LinkedIn.Tokens(new Extensions.LinkedIn.Auth(txtLinkedInApiKey, txtLinkedInApiSecret, "", Request.Url.AbsoluteUri));
                return Redirect(HttpUtility.UrlDecode(auth.GetRequestURL()));
            }
        }

        public ActionResult oauth()
        {
            if (Request["code"] == null)
                throw new Exception("Invalid auth codes.");

            var txtLinkedInApiKey = TempData["txtLinkedInApiKey"].ToString();
            var txtLinkedInApiSecret = TempData["txtLinkedInApiSecret"].ToString();
            var redirectUri = System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority) + System.Web.HttpContext.Current.Request.Url.AbsolutePath;
            if (string.IsNullOrEmpty(txtLinkedInApiKey) && string.IsNullOrEmpty(txtLinkedInApiSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getaccesstokens/{0}?returnurl={2}&linkedinCode={1}",
                                  new Extensions.LinkedIn.Identity().Code,
                                  Request["code"],
                                  redirectUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var token = JsonConvert.DeserializeObject<Dictionary<string, string>>(rs.Content.ReadAsStringAsync().Result);

                ViewBag.LinkedInAccessToken = token["AccessToken"];
            }
            else
            {
                var auth = new Extensions.LinkedIn.Tokens(new Extensions.LinkedIn.Auth(txtLinkedInApiKey, txtLinkedInApiSecret, "", redirectUri));
                var token = auth.GetAccessToken(Request["code"]);

                ViewBag.LinkedInAccessToken = token;
            }

            return View("OAuthComplete");
        }
    }
}

source/FlowplaneExtensions/Views/LinkedIn/Auth.cshtml
<script>
    var linkedinAuthPopup = function () {
        var w = 1000;
        var h = 640;
        var left = (screen.width / 2) - (w / 2);
        var top = (screen.height / 2) - (h / 2);
        window.open("about:blank",
			"frmLinkedInAuth",
                "width=" + w + ", height=" + h + ", top=" + top + ", left=" + left + ", toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no");
        document.getElementById('frm-linkedin-app-keys').submit();
    }
    $(document).ready(function () {
        $('#chkLinkedInOauthOption').bootstrapSwitch().on('switchChange.bootstrapSwitch', function (event, state) {
            if (state == false) {
                $('.linkedin-app-keys').show();
                $('#txtLinkedInApiKey').focus();
            } else {
                $('.linkedin-app-keys').hide();
            }
        });
    });
</script>

<p>
    <img src="@Url.Content("~/Content/img/ext-linkedin.png")" />
    &nbsp;
    Connect to your LinkedIn account.
</p>
<div id="btnConnectLinkedIn" class="row" style="margin-top: 20px;">
    <div class="col-md-6">
        <p>
            Oauth with Flowplane:&nbsp;
            <input type="checkbox" id="chkLinkedInOauthOption" data-size="medium" data-on-text="Yes" data-off-text="No" checked>
        </p>
        <form id="frm-linkedin-app-keys" method="post" action="@Url.Action("oauth", "LinkedIn")" target="frmLinkedInAuth">
            <div class="linkedin-app-keys form-group" style="display: none; margin-bottom: 20px;">
                <label>
                    Api Key:
                </label>
                <input id="txtLinkedInApiKey" name="txtLinkedInApiKey" class="form-control" autocomplete="off" placeholder="Api Key" type="text" value="" />
            </div>
            <div class="linkedin-app-keys form-group" style="display: none;">
                <label>
                    Secret Key:
                </label>
                <input id="txtLinkedInApiSecret" name="txtLinkedInApiSecret" class="form-control" autocomplete="off" placeholder="Secret Key" type="text" value="" />
            </div>
        </form>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-3">
        <a href="javascript:;"
           onclick="linkedinAuthPopup();"
           class="btn green" target="_top">Connect to LinkedIn</a>
    </div>
</div>

<input id="txtLinkedInAccessToken" name="txtLinkedInAccessToken" style="display:none;" type="text" value="" />
<h4 id="lblConnectedToLinkedIn" style="display: none;"><i class="fa fa-check"></i>&nbsp; Connected.</h4>

source/FlowplaneExtensions/Views/LinkedIn/Body.cshtml
<form class="form-horizontal" role="form">
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div id="dlg-ProcObjProperties-error" class="col-sm-8" style="color: #c00;"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Share an Update on LinkedIn:
        </label>
        <div class="col-sm-8">
            <textarea id="txtEventParamShareStatus" name="txtEventParamShareStatus" placeholder="Write to LinkedIn (required)" maxlength="140"
                      style="resize: none; width: 100%; min-height: 140px; max-height: 140px; min-width: 100%; max-width: 100%;"
                      class="form-control"></textarea>
        </div>
    </div>
</form>

source/FlowplaneExtensions/Views/LinkedIn/Header.cshtml
<h4>
    <img src="@Url.Content("~//Content/img/ext-linkedin.png")" />
    &nbsp; LinkedIn
</h4>

source/FlowplaneExtensions/Views/LinkedIn/OAuthComplete.cshtml
<html>
<head>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
    <script>
        window.opener.document.getElementById('txtLinkedInAccessToken').value = '@Html.Raw(ViewBag.LinkedInAccessToken)';

        var btn = $(window.opener.document).find('#btnConnectLinkedIn');
        var lbl = $(window.opener.document).find('#lblConnectedToLinkedIn');
        $(btn).hide();
        $(lbl).show();

        window.close();
    </script>
</head>
<body>
</body>
</html>