source/FlowplaneExtensions/Controllers/FacebookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Extensions.Asana.Responses.Projects;
using FlowplaneExtensions.Models.api;
using FlowplaneExtensions.Models.api.Flow;
using Newtonsoft.Json;

namespace FlowplaneExtensions.Controllers
{
    public class FacebookController : Controller
    {
        public ActionResult Auth()
        {
            return View();
        }

        public ActionResult Header()
        {
            return View();
        }

        public ActionResult Body()
        {
            return View();
        }

        [HttpPost]
        public ActionResult oauth(string txtFacebookAppId, string txtFacebookAppSecret)
        {
            TempData["txtFacebookAppId"] = txtFacebookAppId;
            TempData["txtFacebookAppSecret"] = txtFacebookAppSecret;

            if (string.IsNullOrEmpty(txtFacebookAppId) && string.IsNullOrEmpty(txtFacebookAppSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getloginurl/{0}?returnurl={1}",
                                  new Extensions.Facebook.Identity().Code, Request.Url.AbsoluteUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                var url = JsonConvert.DeserializeObject<string>(rs.Content.ReadAsStringAsync().Result);

                return Redirect(HttpUtility.UrlDecode(url));
            }
            else
            {
                var auth = new Extensions.Facebook.Auth();
                return Redirect(HttpUtility.UrlDecode(auth.GetLoginUrl(txtFacebookAppId, txtFacebookAppSecret, Request.Url.AbsoluteUri)));
            }
        }

        public ActionResult oauth()
        {
            if (Request["code"] == null)
                throw new Exception("Invalid auth code.");

            var txtFacebookAppId = TempData["txtFacebookAppId"].ToString();
            var txtFacebookAppSecret = TempData["txtFacebookAppSecret"].ToString();

            if (string.IsNullOrEmpty(txtFacebookAppId) && string.IsNullOrEmpty(txtFacebookAppSecret))
            {
                // use flowplane
                var httpClient = new HttpClient();
                var rs = httpClient.GetAsync(
                    string.Format(Common.FlowplaneDotCom + "/api/oauth/getaccesstokens/{0}?returnurl={2}&facebookCode={1}",
                                  new Extensions.Facebook.Identity().Code, 
                                  Request["code"], 
                                  Request.Url.AbsoluteUri)).Result;
                if (!rs.IsSuccessStatusCode) throw new Exception(rs.ReasonPhrase);

                ViewBag.AccessToken = JsonConvert.DeserializeObject<Dictionary<string, string>>(rs.Content.ReadAsStringAsync().Result)["AccessToken"];
            }
            else
            {
                var auth = new Extensions.Facebook.Auth();
                ViewBag.AccessToken = auth.GetAccessToken(txtFacebookAppId, txtFacebookAppSecret, Request["code"], Request.Url.AbsoluteUri);
            }

            return View("OAuthComplete");
        }

        public ActionResult FlowDetail(string fpxtpms)
        {
            if (string.IsNullOrEmpty(fpxtpms)) return View();

            ViewBag.pms = fpxtpms;
            return View(JsonConvert.DeserializeObject<Detail>(System.Uri.UnescapeDataString(fpxtpms)));
        }
    }
}

source/FlowplaneExtensions/Views/Facebook/Auth.cshtml
<script>
	var facebookAuthPopup = function () {
		var w = 1000;
		var h = 640;
		var left = (screen.width / 2) - (w / 2);
		var top = (screen.height / 2) - (h / 2);
		window.open("about:blank",
			"frmFacebookAuth",
			"width=" + w + ", height=" + h + ", top=" + top + ", left=" + left + ", toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=no, resizable=no, copyhistory=no");
		document.getElementById('frm-facebook-app-keys').submit();
	};
	$(document).ready(function () {
		$('#chkFacebookOauthOption').bootstrapSwitch().on('switchChange.bootstrapSwitch', function (event, state) {
			if (state == false) {
				$('.facebook-app-keys').show();
				$('#txtFacebookAppId').focus();
			} else {
				$('.facebook-app-keys').hide();
			}
		});
	});
</script>
<p>
	<img src="@System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~//Content/img/ext-facebook.png")" />
	&nbsp;
	Connect to your Facebook account.
</p>
<div id="btnConnectFacebook" class="row" style="margin-top: 20px;">
	<div class="col-md-6">
		<p>
			Oauth with Flowplane:&nbsp;
			<input type="checkbox" id="chkFacebookOauthOption" data-size="medium" data-on-text="Yes" data-off-text="No" checked>
		</p>
		<form id="frm-facebook-app-keys" method="post" action="@Url.Action("oauth", "Facebook")" target="frmFacebookAuth">
			<div class="facebook-app-keys" class="form-group" style="display: none; margin-bottom: 20px;">
				<label>
					App Id:
				</label>
				<input id="txtFacebookAppId" name="txtFacebookAppId" class="form-control" autocomplete="off" placeholder="App Id" type="text" value="" />
			</div>
			<div class="facebook-app-keys" class="form-group" style="display: none;">
				<label>
					App Secret:
				</label>
				<input id="txtFacebookAppSecret" name="txtFacebookAppSecret" class="form-control" autocomplete="off" placeholder="App Secret" type="text" value="" />
			</div>
		</form>
	</div>
	<div class="col-md-1"></div>
	<div class="col-md-3">
		<a href="javascript:;"
		   onclick="facebookAuthPopup();"
		   class="btn green" target="_top">Connect to Facebook</a>
	</div>
</div>

<input id="txtFacebookAccessToken" name="txtFacebookAccessToken" style="visibility: hidden;" type="text" value="" />
<h4 id="lblConnectedToFacebook" style="display: none;"><i class="fa fa-check"></i>&nbsp; Connected.</h4>

source/FlowplaneExtensions/Views/Facebook/Body.cshtml
<form class="form-horizontal" role="form">
    <div class="form-group">
        <div class="col-sm-2"></div>
        <div id="dlg-ProcObjProperties-error" class="col-sm-8" style="color: #c00;"></div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">
            Post status:
        </label>
        <div class="col-sm-8">
            <textarea id="txtEventParamFacebookStatus" name="txtEventParamFacebookStatus" placeholder="Facebook status (required)" maxlength="140"
                      style="resize: none; width: 100%; min-height: 140px; max-height: 140px; min-width: 100%; max-width: 100%;"
                      class="form-control"></textarea>
        </div>
    </div>
</form>

source/FlowplaneExtensions/Views/Facebook/FlowDetail.cshtml
@model FlowplaneExtensions.Models.api.Flow.Detail

<script src='@Url.Content("~/Content/js/moment/moment.js")' type='text/javascript'></script>
<script src='@Url.Content("~/Content/js/forms/apptools.js")' type='text/javascript'></script>
<script>
    $(document).ready(function () {
        fpxt.forms.apptools.fmtDate($('#dtStarted'), 'll');
    });
</script>

<h5><i class="fa fa-facebook-square fa-2x" style="margin-right: 10px; color: #3B5998;"></i>Facebook Event</h5>

<p>
    Facebook status:<br />
</p>
<p>
    @Model.GetParamValue("facebookstatus")
</p>
@if (Model.DateCreated != null)
{
    <p>
        Raised: 
        <span id="dtStarted">@Convert.ToDateTime(Model.DateCreated).ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'")</span>
    </p>
}

source/FlowplaneExtensions/Views/Facebook/Header.cshtml
<h4>
    <img src="@System.Web.HttpContext.Current.Request.Url.GetLeftPart(UriPartial.Authority)@Url.Content("~//Content/img/ext-facebook.png")" />
    &nbsp; Facebook
</h4>

source/FlowplaneExtensions/Views/Facebook/OAuthComplete.cshtml
<html>
<head>
    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>
    <script>
        window.opener.document.getElementById('txtFacebookAccessToken').value = '@Html.Raw(ViewBag.AccessToken)';

        var btn = $(window.opener.document).find('#btnConnectFacebook');
        var lbl = $(window.opener.document).find('#lblConnectedToFacebook');
        $(btn).hide();
        $(lbl).show();

        window.close();
    </script>
</head>
<body>
</body>
</html>